version: '3.8'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15}
    container_name: ${PROJECT_NAME:-duunoii}-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-duunoii}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-duunoii_db}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:${REDIS_VERSION:-7-alpine}
    container_name: ${PROJECT_NAME:-duunoii}-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # MinIO for S3-compatible local storage (optional)
  minio:
    image: minio/minio:${MINIO_VERSION:-latest}
    container_name: ${PROJECT_NAME:-duunoii}-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data: